### ISSUE TITLE
Unable to create new release

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/synthtool#30]
After running `releasetool tag`, I am getting the following error:

```
Which one do you want to tag and release?: 1
> Determining what the release tag should be.
Release tag is synthtool-0.3.1.
> Determining the package name and version.
Package name: synthtool, package version: 0.3.1.
> Grabbing the release notes.
> Creating the release.
Release is at https://github.com/GoogleCloudPlatform/synthtool/releases/tag/synthtool-0.3.1
> Publishing to PyPI.
warning: check: missing required meta-data: url

Traceback (most recent call last):
  File "/Users/beckwith/Library/Python/3.6/bin/releasetool", line 11, in <module>
    load_entry_point('gcp-releasetool==0.2.1', 'console_scripts', 'releasetool')()
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/releasetool/main.py", line 56, in tag
    return releasetool.commands.tag.python_tool.tag()
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/releasetool/commands/tag/python_tool.py", line 88, in tag
    publish_to_pypi(ctx)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/releasetool/commands/tag/python_tool.py", line 69, in publish_to_pypi
    subprocess.check_call(['twine', 'upload'] + dists)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'twine': 'twine'
```

**Comment by busunkim96** [comment]
Releasetool no longer uses twine as of version 0.8.0
